[package]
name = "simple_web_server"
version = "0.1.0"
authors = ["hskang9 <hskang9@gmail.com>"]
edition = "2018"

[dependencies]
jsonrpc-core = "10.0.1"
jsonrpc-http-server = "10.0.1"
jsonrpc-derive = "10.0.2"
