[package]
name = "rust_crypto"
version = "0.1.0"
authors = ["hskang9 <hskang9@gmail.com>"]
edition = "2018"

[dependencies]
serde = {version = "1.0.87", features = ["derive"] }
secp256k1 = {version="0.12.2", features= ["rand"]}
rand = "0.4"
hex = "0.3.1"
rust-crypto = "0.2.36"
chrono = "0.4.0"